import os

import torch


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

DIV2K_TRAIN_PATH = "./dataset/train"
KODAK_TEST_PATH = "./dataset/test"

MODEL_SAVE_PATH = "./checkpoints"
LOG_PATH = "./logs"
RECON_IMAGE_PATH = "./recon_images"

BATCH_SIZE = 8
TEST_BATCH_SIZE = 1
EPOCHS = 100
LEARNING_RATE = 2e-5
AUX_LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-5
SEMANTIC_LR_MULTIPLIER = 10.0

IMAGE_SIZE = 256
VAL_SPLIT = 0.1
RANDOM_SEED = 42

VIT_QUALITY = 6
VIT_PRETRAINED = True
CLIP_MODEL_NAME = "ViT-B/32"
CLIP_EMBED_DIM = 512
DECODER_FEAT_DIMS = [384]
MODEL_ARCH_VERSION = "compressai_semantic_v10"

PERCEPTUAL_LOSS_WEIGHT = 0.10
MSE_LOSS_WEIGHT = 0.90
RATE_LOSS_WEIGHT = 0.01
SEMANTIC_LOSS_WEIGHT = 1.0
SEMANTIC_CONTRASTIVE_WEIGHT = 0.5
SEMANTIC_CONTRASTIVE_TEMPERATURE = 0.07
SEMANTIC_MISMATCH_WEIGHT = 2.0
SEMANTIC_MISMATCH_MARGIN = 0.02
ALEX_LPIPS_LOSS_WEIGHT = 10.0
ALEX_LPIPS_GAP_MARGIN = 0.0005
ALEX_LPIPS_GAP_WEIGHT = 100.0

SAVE_RECON_IMAGES = True
SAVE_BEST_MODEL_ONLY = True


def init_directories():
    for dir_path in (MODEL_SAVE_PATH, LOG_PATH, RECON_IMAGE_PATH):
        os.makedirs(dir_path, exist_ok=True)


init_directories()
